// Emoji 数据
const emojiData = {
    smileys: [
        { emoji: "😀", name: "笑脸", keywords: ["smile", "happy", "joy", "笑", "高兴"] },
        { emoji: "😃", name: "大笑", keywords: ["laugh", "happy", "joy", "大笑", "开心"] },
        { emoji: "😄", name: "眯眼笑", keywords: ["smile", "laugh", "happy", "眯眼", "开心"] },
        { emoji: "😁", name: "露齿笑", keywords: ["grin", "happy", "joy", "露齿", "开心"] },
        { emoji: "😆", name: "大笑", keywords: ["laugh", "happy", "joy", "大笑", "开心"] },
        { emoji: "😅", name: "汗颜笑", keywords: ["sweat", "smile", "汗", "尴尬"] },
        { emoji: "🤣", name: "笑倒", keywords: ["rofl", "laugh", "笑倒", "大笑"] },
        { emoji: "😂", name: "笑哭", keywords: ["joy", "tears", "笑哭", "开心"] },
        { emoji: "🙂", name: "微笑", keywords: ["smile", "微笑", "友好"] },
        { emoji: "🙃", name: "倒脸", keywords: ["upside-down", "倒脸", "幽默"] },
        { emoji: "😉", name: "眨眼", keywords: ["wink", "眨眼", "暗示"] },
        { emoji: "😊", name: "含笑", keywords: ["blush", "smile", "含笑", "害羞"] },
        { emoji: "😇", name: "天使笑", keywords: ["angel", "innocent", "天使", "纯洁"] },
        { emoji: "🥰", name: "爱心笑", keywords: ["love", "hearts", "爱心", "喜欢"] },
        { emoji: "😍", name: "星星眼", keywords: ["love", "heart-eyes", "星星眼", "喜欢"] },
        { emoji: "🤩", name: "星光眼", keywords: ["star-struck", "excited", "星光", "兴奋"] }
    ],
    people: [
        { emoji: "👶", name: "婴儿", keywords: ["baby", "child", "婴儿", "孩子"] },
        { emoji: "👧", name: "女孩", keywords: ["girl", "child", "女孩", "孩子"] },
        { emoji: "👦", name: "男孩", keywords: ["boy", "child", "男孩", "孩子"] },
        { emoji: "👩", name: "女人", keywords: ["woman", "female", "女人", "女性"] },
        { emoji: "👨", name: "男人", keywords: ["man", "male", "男人", "男性"] },
        { emoji: "👵", name: "老奶奶", keywords: ["old woman", "grandma", "老奶奶", "祖母"] },
        { emoji: "👴", name: "老爷爷", keywords: ["old man", "grandpa", "老爷爷", "祖父"] },
        { emoji: "👮", name: "警察", keywords: ["police", "cop", "警察", "执法"] },
        { emoji: "👷", name: "工人", keywords: ["worker", "construction", "工人", "建筑"] },
        { emoji: "💂", name: "卫兵", keywords: ["guard", "卫兵", "守卫"] },
        { emoji: "🕵️", name: "侦探", keywords: ["detective", "spy", "侦探", "间谍"] },
        { emoji: "👩‍⚕️", name: "女医生", keywords: ["doctor", "nurse", "医生", "护士"] },
        { emoji: "👨‍⚕️", name: "男医生", keywords: ["doctor", "医生", "医护"] },
        { emoji: "👩‍🎓", name: "女学生", keywords: ["student", "graduate", "学生", "毕业生"] },
        { emoji: "👨‍🎓", name: "男学生", keywords: ["student", "graduate", "学生", "毕业生"] },
        { emoji: "👩‍🏫", name: "女老师", keywords: ["teacher", "professor", "老师", "教授"] }
    ],
    animals: [
        { emoji: "🐶", name: "狗", keywords: ["dog", "pet", "狗", "宠物"] },
        { emoji: "🐱", name: "猫", keywords: ["cat", "pet", "猫", "宠物"] },
        { emoji: "🐭", name: "老鼠", keywords: ["mouse", "rat", "老鼠", "鼠"] },
        { emoji: "🐹", name: "仓鼠", keywords: ["hamster", "pet", "仓鼠", "宠物"] },
        { emoji: "🐰", name: "兔子", keywords: ["rabbit", "bunny", "兔子", "兔"] },
        { emoji: "🦊", name: "狐狸", keywords: ["fox", "狐狸", "动物"] },
        { emoji: "🐻", name: "熊", keywords: ["bear", "熊", "动物"] },
        { emoji: "🐼", name: "熊猫", keywords: ["panda", "熊猫", "国宝"] },
        { emoji: "🐨", name: "考拉", keywords: ["koala", "考拉", "动物"] },
        { emoji: "🐯", name: "老虎", keywords: ["tiger", "老虎", "虎"] },
        { emoji: "🦁", name: "狮子", keywords: ["lion", "狮子", "狮"] },
        { emoji: "🐮", name: "牛", keywords: ["cow", "ox", "牛", "动物"] },
        { emoji: "🐷", name: "猪", keywords: ["pig", "猪", "动物"] },
        { emoji: "🐸", name: "青蛙", keywords: ["frog", "青蛙", "蛙"] },
        { emoji: "🐵", name: "猴子", keywords: ["monkey", "猴子", "猴"] },
        { emoji: "🐔", name: "鸡", keywords: ["chicken", "rooster", "鸡", "公鸡"] }
    ],
    food: [
        { emoji: "🍎", name: "红苹果", keywords: ["apple", "fruit", "苹果", "水果"] },
        { emoji: "🍐", name: "梨", keywords: ["pear", "fruit", "梨", "水果"] },
        { emoji: "🍊", name: "橘子", keywords: ["orange", "fruit", "橘子", "水果"] },
        { emoji: "🍋", name: "柠檬", keywords: ["lemon", "fruit", "柠檬", "水果"] },
        { emoji: "🍌", name: "香蕉", keywords: ["banana", "fruit", "香蕉", "水果"] },
        { emoji: "🍉", name: "西瓜", keywords: ["watermelon", "fruit", "西瓜", "水果"] },
        { emoji: "🍇", name: "葡萄", keywords: ["grapes", "fruit", "葡萄", "水果"] },
        { emoji: "🍓", name: "草莓", keywords: ["strawberry", "fruit", "草莓", "水果"] },
        { emoji: "🍈", name: "甜瓜", keywords: ["melon", "fruit", "甜瓜", "水果"] },
        { emoji: "🍒", name: "樱桃", keywords: ["cherries", "fruit", "樱桃", "水果"] },
        { emoji: "🍑", name: "桃子", keywords: ["peach", "fruit", "桃子", "水果"] },
        { emoji: "🥭", name: "芒果", keywords: ["mango", "fruit", "芒果", "水果"] },
        { emoji: "🍍", name: "菠萝", keywords: ["pineapple", "fruit", "菠萝", "水果"] },
        { emoji: "🥥", name: "椰子", keywords: ["coconut", "fruit", "椰子", "水果"] },
        { emoji: "🥝", name: "猕猴桃", keywords: ["kiwi", "fruit", "猕猴桃", "水果"] },
        { emoji: "🍅", name: "番茄", keywords: ["tomato", "vegetable", "番茄", "蔬菜"] }
    ],
    travel: [
        { emoji: "🚗", name: "汽车", keywords: ["car", "vehicle", "汽车", "车辆"] },
        { emoji: "🚕", name: "出租车", keywords: ["taxi", "cab", "出租车", "的士"] },
        { emoji: "🚌", name: "公交车", keywords: ["bus", "公交车", "巴士"] },
        { emoji: "🚎", name: "有轨电车", keywords: ["trolleybus", "有轨电车", "电车"] },
        { emoji: "🏎️", name: "赛车", keywords: ["racing car", "赛车", "跑车"] },
        { emoji: "🚓", name: "警车", keywords: ["police car", "警车", "巡逻车"] },
        { emoji: "🚑", name: "救护车", keywords: ["ambulance", "救护车", "急救"] },
        { emoji: "🚒", name: "消防车", keywords: ["fire engine", "消防车", "灭火"] },
        { emoji: "🚚", name: "货车", keywords: ["truck", "delivery", "货车", "运输"] },
        { emoji: "✈️", name: "飞机", keywords: ["airplane", "plane", "飞机", "航空"] },
        { emoji: "🚀", name: "火箭", keywords: ["rocket", "spaceship", "火箭", "宇宙飞船"] },
        { emoji: "🛸", name: "飞碟", keywords: ["ufo", "飞碟", "不明飞行物"] },
        { emoji: "🚁", name: "直升机", keywords: ["helicopter", "直升机", "飞机"] },
        { emoji: "⛵", name: "帆船", keywords: ["sailboat", "帆船", "船"] },
        { emoji: "🚢", name: "轮船", keywords: ["ship", "boat", "轮船", "船"] },
        { emoji: "🚂", name: "蒸汽火车", keywords: ["locomotive", "train", "火车", "蒸汽"] }
    ],
    activities: [
        { emoji: "⚽", name: "足球", keywords: ["soccer", "football", "足球", "运动"] },
        { emoji: "🏀", name: "篮球", keywords: ["basketball", "篮球", "运动"] },
        { emoji: "🏈", name: "美式足球", keywords: ["football", "美式足球", "运动"] },
        { emoji: "⚾", name: "棒球", keywords: ["baseball", "棒球", "运动"] },
        { emoji: "🎾", name: "网球", keywords: ["tennis", "网球", "运动"] },
        { emoji: "🏐", name: "排球", keywords: ["volleyball", "排球", "运动"] },
        { emoji: "🏉", name: "橄榄球", keywords: ["rugby", "橄榄球", "运动"] },
        { emoji: "🎱", name: "台球", keywords: ["billiards", "pool", "台球", "运动"] },
        { emoji: "🏓", name: "乒乓球", keywords: ["ping pong", "table tennis", "乒乓球", "运动"] },
        { emoji: "🏸", name: "羽毛球", keywords: ["badminton", "羽毛球", "运动"] },
        { emoji: "🥅", name: "球门", keywords: ["goal net", "球门", "运动"] },
        { emoji: "⛳", name: "高尔夫旗", keywords: ["golf", "高尔夫", "运动"] },
        { emoji: "🎣", name: "钓鱼", keywords: ["fishing", "钓鱼", "休闲"] },
        { emoji: "🎽", name: "跑步衫", keywords: ["running shirt", "跑步", "运动"] },
        { emoji: "🎿", name: "滑雪", keywords: ["ski", "滑雪", "冬季运动"] },
        { emoji: "🛷", name: "雪橇", keywords: ["sled", "雪橇", "冬季运动"] }
    ],
    objects: [
        { emoji: "⌚", name: "手表", keywords: ["watch", "time", "手表", "时间"] },
        { emoji: "📱", name: "手机", keywords: ["mobile phone", "smartphone", "手机", "智能手机"] },
        { emoji: "💻", name: "笔记本电脑", keywords: ["laptop", "computer", "笔记本", "电脑"] },
        { emoji: "⌨️", name: "键盘", keywords: ["keyboard", "键盘", "输入"] },
        { emoji: "🖥️", name: "台式电脑", keywords: ["desktop", "computer", "台式机", "电脑"] },
        { emoji: "🖨️", name: "打印机", keywords: ["printer", "打印机", "办公"] },
        { emoji: "🖱️", name: "鼠标", keywords: ["mouse", "鼠标", "电脑"] },
        { emoji: "🕹️", name: "游戏手柄", keywords: ["joystick", "游戏", "手柄"] },
        { emoji: "💾", name: "软盘", keywords: ["floppy disk", "软盘", "存储"] },
        { emoji: "💿", name: "光盘", keywords: ["cd", "optical disc", "光盘", "存储"] },
        { emoji: "📀", name: "DVD", keywords: ["dvd", "disc", "DVD", "光盘"] },
        { emoji: "📷", name: "相机", keywords: ["camera", "photo", "相机", "照片"] },
        { emoji: "📹", name: "摄像机", keywords: ["video camera", "摄像机", "视频"] },
        { emoji: "🎥", name: "电影摄像机", keywords: ["movie camera", "film", "电影", "摄像机"] },
        { emoji: "📺", name: "电视", keywords: ["tv", "television", "电视", "电视机"] },
        { emoji: "📻", name: "收音机", keywords: ["radio", "收音机", "广播"] },
        { emoji: "🎙️", name: "麦克风", keywords: ["microphone", "mic", "麦克风", "话筒"] },
        { emoji: "🎧", name: "耳机", keywords: ["headphone", "earphone", "耳机", "听音乐"] },
        { emoji: "📞", name: "电话", keywords: ["telephone", "phone", "电话", "通讯"] },
        { emoji: "🔋", name: "电池", keywords: ["battery", "电池", "能源"] }
    ],
    symbols: [
        { emoji: "❤️", name: "红心", keywords: ["heart", "love", "红心", "爱"] },
        { emoji: "💔", name: "碎心", keywords: ["broken heart", "碎心", "伤心"] },
        { emoji: "💯", name: "满分", keywords: ["hundred", "score", "满分", "一百分"] },
        { emoji: "✅", name: "复选标记", keywords: ["check", "tick", "复选", "正确"] },
        { emoji: "❌", name: "叉号", keywords: ["cross", "x", "叉号", "错误"] },
        { emoji: "⭕", name: "圆圈", keywords: ["circle", "圆圈", "圆"] },
        { emoji: "⚠️", name: "警告", keywords: ["warning", "caution", "警告", "注意"] },
        { emoji: "🚫", name: "禁止", keywords: ["prohibited", "forbidden", "禁止", "不允许"] },
        { emoji: "🔞", name: "18禁", keywords: ["18", "prohibited", "18禁", "成人"] },
        { emoji: "📛", name: "姓名牌", keywords: ["name badge", "姓名牌", "标识"] },
        { emoji: "🔠", name: "大写字母", keywords: ["uppercase", "capital", "大写", "字母"] },
        { emoji: "🔡", name: "小写字母", keywords: ["lowercase", "小写", "字母"] },
        { emoji: "🔢", name: "数字", keywords: ["numbers", "数字", "数学"] },
        { emoji: "🔣", name: "符号", keywords: ["symbols", "符号", "标点"] },
        { emoji: "🔤", name: "字母", keywords: ["letters", "abc", "字母", "英文"] },
        { emoji: "ℹ️", name: "信息", keywords: ["information", "info", "信息", "资讯"] }
    ],
    // 在flags分类中确保emoji字段包含国旗表情符号，而不是国家代码
    flags: [
        { emoji: "🇨🇳", name: "中国", keywords: ["China", "flag", "中国", "国旗"] },
        { emoji: "🇺🇸", name: "美国", keywords: ["USA", "flag", "美国", "国旗"] },
        { emoji: "🇬🇧", name: "英国", keywords: ["UK", "flag", "英国", "国旗"] },
        { emoji: "🇯🇵", name: "日本", keywords: ["Japan", "flag", "日本", "国旗"] },
        { emoji: "🇰🇷", name: "韩国", keywords: ["Korea", "flag", "韩国", "国旗"] },
        { emoji: "🇫🇷", name: "法国", keywords: ["France", "flag", "法国", "国旗"] },
        { emoji: "🇩🇪", name: "德国", keywords: ["Germany", "flag", "德国", "国旗"] },
        { emoji: "🇮🇹", name: "意大利", keywords: ["Italy", "flag", "意大利", "国旗"] },
        { emoji: "🇪🇸", name: "西班牙", keywords: ["Spain", "flag", "西班牙", "国旗"] },
        { emoji: "🇷🇺", name: "俄罗斯", keywords: ["Russia", "flag", "俄罗斯", "国旗"] },
        { emoji: "🇧🇷", name: "巴西", keywords: ["Brazil", "flag", "巴西", "国旗"] },
        { emoji: "🇦🇺", name: "澳大利亚", keywords: ["Australia", "flag", "澳大利亚", "国旗"] },
        { emoji: "🇨🇦", name: "加拿大", keywords: ["Canada", "flag", "加拿大", "国旗"] },
        { emoji: "🇮🇳", name: "印度", keywords: ["India", "flag", "印度", "国旗"] },
        { emoji: "🇲🇽", name: "墨西哥", keywords: ["Mexico", "flag", "墨西哥", "国旗"] },
        { emoji: "🏳️", name: "白旗", keywords: ["white flag", "surrender", "白旗", "投降"] }
    ]
};
